### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by atuz86** [atuz86/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by alex-tuz** [comment]
Ryu is a silent, meek, humble, submissive, self-deprecating, and respectful individual. For Ryu, the training and the mastery that comes from the fight are all that he requires for satisfaction, declining the more material trappings of his various accomplishments as a warrior, simply moving on to his next challenge once he is victorious without delay, unless he is offered food or if he wants to converse with his friendly rivals. This attitude may be seen as part Zeno's approach in Stoicism rather than an appeal by one man to others after losing something precious during battle (Chomsky 1991: 542). Some scholars have suggested this idea has nothing at present directly to do wit with Japanese Samurai values but instead their socialization processes; it was not unheard before within Japan what appeared ungrateful individuals might get angry when they were told too much about another samurai hero yet continued using them due almost certainly because these new warriors had been trained under such harsh conditions while thus becoming comfortable again being expected "to make everything right" through violence alone (Fukada 1999).

**Comment by atuz86** [comment]
Thanks!
