### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by atuz86** [atuz86/homepage#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by alex-tuz** [comment]
Pre-Street Fighter

Ryu & Gouken

As a very young child, Ryu was orphaned and left with no memories of his parents, and whether they were still alive. He was found and adopted by a man named Gouken who raised Ryu in his secluded dojo and trained Ryu in the ways of his martial arts. Ryu used to watch Gouken, Goutetsu and Akuma train with each other.[29] Sometime afterwards, Gouken would later train his best friend's spoiled son, Ken Masters. Ken served not only as a sparring partner, but also gave Ryu a friend in the form of a boy his own age. Ryu looked up to Gouken as a father figure, and regards Ken as his best friend and surrogate brother, a relationship which remains to this day.

When Ryu turned 23 years old, Gouken believed that Ryu was ready to travel the world in order to test and hone his martial skills against the best fighters from around the world. After Ryu and Ken's training was complete, Ken casually asks Ryu which of the two will be recognized as reputable martial artists first. While Ken goes to USA, Ryu enters the World Warrior tournament and travels to Thailand alone, in order to face Sagat the Emperor of Muay Thai which is said to be the strongest martial art. [13][30]

The first World Warrior tournament
Main article: Street Fighter

Ryu defeats Sagat using Shoryuken.

Ryu is one of the participants of the World Warrior tournament. After defeating all challengers, Ryu travels to Thailand. When Ryu arrived, he knew he couldn't just challenge Sagat as an unknown fighter, so Ryu created a plan to put Sagat in a situation where he can't refuse his challenge.[13][31] By defeating many Muay Thai fighters, he believed it'll eventually reach Sagat's ears. If successful, Sagat will show himself in order to defend Muay Thai's honor.[13][32] Ryu defeats 20 Muay Thai users, and yells at the fighters how allowing a stranger to tarnish Muay Thai's reputation is an embarrassment, Sagat heard Ryu and his fighting spirit burned. He told Ryu that he'll show him real Muay Thai, and the two would clash.[13][33] Ryu, however, defeats Sagat with a nearly-fatal Shoryuken[34][35][36] that not only knocks Sagat unconscious, but also marks his chest with a great scar. After regaining consciousness and discovering what had happened, Sagat swears vengeance on Ryu.[37][38]

Beginning the battles against Akuma and Bison
Main article: Street Fighter Alpha series

Akuma telling Ryu about the Satsui no Hado.

Ryu leaves Sagat behind and continues training travelling to various location pondering the question "What is the meaning of anything in life?".[39] He encounters and fights Akuma on a secluded island known as Gokuentou, and wins; however, Akuma was only testing him, and senses that Ryu has the same powers as he does. He proceeds to tell Ryu about the Satsui no Hado - a power that consumes the practitioners of their shared fighting style, driving them to win even when it means killing the opponent. Akuma then uses his fist to smash the island, leaving Ryu stranded.[39]


Ken gives Ryu his headband.

Sometime after escaping the island, Ryu battles Ken and loses. Ken realizes Ryu is not himself, as he has been deeply troubled since his last victory over Sagat. Ken gives him his red hairband as a reminder to stay focused, which Ryu was sincerely grateful for. Soon thereafter, a fan of his, named Sakura, comes up and expresses her desire to train under him. Ryu replies that he himself still has much to learn, but allows Sakura to take a picture of him for now.


Sagat reflecting on his fight with Ryu.

At some point, Ryu is found by Sagat, who is out for a grudge match. Ryu protests that Sagat hasn't fully recovered from their last bout, but Sagat persists. Ryu lets Sagat win rather than do any further damage, and Sagat leaves. Only later, upon reflection, does Sagat realize that Ryu held back, vowing to fight him again.[40]

Ryu continues to be troubled by what Akuma had told him, compounded by his encounter with Rose, who has intricate ties to M. Bison. She tells him that he cannot defeat Bison unless he fights him at the cost of his soul. True to form, when Ryu confronts Bison, he is defeated despite putting up a valiant fight. Bison takes the semi-conscious Ryu and begins brainwashing him, using the revelation that the Satsui no Hado - the dark power Ryu struggles to avoid using - is akin to Bison's own Psycho Power.

This scene is interrupted by the entrance of Sagat, Ken, and Sakura, each of them having followed Ryu for their own reasons. While Ken and Sakura distract Bison, Sagat fights the brainwashed Ryu, quickly noticing the effects Bison's brainwashing has had on him. At Sagat's urging, Ryu comes to his senses to confront and defeat Bison, destroying him temporarily.

Second world warrior tournament and Bison's return
Main article: Street Fighter II series
During the World Warrior tournament, Ryu enters to test his skills, and defeats many of the new warriors. He encourages Ken to re-enter as well. It is unknown how far Ryu himself progressed in the tournament, only in the English translation of Street Fighter: Eternal Challenge is it implied he may have lost to Ken. However, Ken's promise to Eliza doesn't exist in any other source or the original text of Eternal Challenge. In Gamest 255 it mentions Ryu avoiding M. Bison's flaming remnants after his body was destroyed by Akuma hinting that Ryu made to the finals.[41]

In Street Fighter IV: Aftermath it shows Ryu helping Guile, Ken, Chun-Li and Cammy defeat Bison. However, Bison refused Guile's offer to surrender himself to the military before unleashing all of his Psycho Power to commit suicide. The animation being canon is unknown as Capcom hasn't mentioned it in other media. Capcom reprinted the All About Street Fighter books for the 30th Anniversary Collection that mentions Akuma defeating M. Bison. Capcom revisits Akuma killing M. Bison in SFV where Akuma's SFII ending is the only one that shows M. Bison being killed, along with SFV April Fools 2019.

In his non-canon ending, he shortly leaves the tournament after he wins against Bison, and revisits his master's grave to tell about his victory and the experiences he had with the other fighters. Ryu then states that the ultimate battle is out there waiting for him and departs, stating that the fight is everything.
