### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by atuz86** [atuz86/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by alex-tuz** [comment]
Ryu's most recognizable attire consists of a white karate gi with the sleeves torn off, medium length hair, a long red headband, a black martial arts belt and bare feet (a choice he makes of his own, believing it to be more comfortable). In many of his appearances, Ryu carries around a large, white duffel bag containing items important to his travels, such as clothing, plane tickets, passports, and local currency.

In the first Street Fighter, Ryu wore a white headband and red shoes. Over the course of time, he has grown taller and more muscular; his karate gi has grown more tattered, his gloves have changed from brown to red and his headband has changed from white to red. Most notably, his hair color has darkened over time; his original Street Fighter appearance gave him red hair, brown in Street Fighter Alpha, dark brown in Street Fighter II, and black in Street Fighter III, Street Fighter IV and Street Fighter V. In the Street Fighter III series, Ryu’s black hair has a blue tint. The red headband Ryu wears was originally worn by Ken. Ryu gave his white headband to Sakura before getting his red headband. From Street Fighter IV onwards, the red gloves worn by Ryu have started to bear stylized writing, which resembles the Fūrinkazan characters on his belt.

In some official Street Fighter II artwork, Ryu's belt has four kanji emblazoned upon the right end: wind (風 Kaze?), forest (林 Hayashi?), fire (火 Hi?) and mountain (山 Yama?); these four kanji make up the Fūrinkazan. The same four kanji can be seen on a sign on the left-hand side of Ryu's stage in Street Fighter II, and are also visible on his belt in Street Fighter IV. The four words are based on chapter seven of Sun Tzu's Art of War, which dictates how one should conduct battle: "as fast as the wind, as quiet as the forest, as daring as fire, and immovable as the mountain."

In Street Fighter II V, Ryu wears some casual outfits throughout the episodes; his primary appearance is a white short-sleeve shirt, blue denim jeans and red and white sneakers. He also has a black watch on his left wrist. Ryu is not wearing his red headband. When he wears his white karate gi, he only wears a brown prayer bead bracelet on his left wrist. He is also more tanned than in the games.

His second alternate costume in Street Fighter V consists of only his white karate pants with a black belt to his waist and tatters in the edge of his pants, gray shoulder bands on each side and hand wraps on his hands. He also has a black facial beard.

During E. Honda's character story, Ryu's black hair was pushed down by the warm water when he was meditating at his bathhouse. By the time he was battling Honda on his bathhouse before he gives him some proper manners after bathing, Ryu wears a white fundoshi without the rear apron and wears a white headband with the sign of red "V" mark at the center instead of his red headband. This also marks the first time to see more of Ryu's bare skin in his revealed appearance as his revealed outfit is the same revealing undergarments currently worn by Cyberbots: Full Metal Madness character, Jin Saotome beneath his main outfit in Marvel vs. Capcom: Clash of Super Heroes and Marvel vs. Capcom 2: New Age of Heroes where he burns his clothes to show this outfit during execution of one of his special moves or his own taunt while drying himself with a white towel.
